spring.application.name=sneaklab

spring.datasource.url=jdbc:postgresql://localhost:5432/sneaklab
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.user.name=admin
spring.security.user.password=admin

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.type=trace

spring.jackson.time-zone=America/Sao_Paulo
spring.jackson.locale=pt_BR

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

server.port=8080
server.servlet.context-path=/api